# Source files for Metal package
set(OCCT_Metal_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Metal_FILES
  Metal_Buffer.hxx
  Metal_Buffer.mm
  Metal_Caps.hxx
  Metal_Caps.mm
  Metal_Clipping.hxx
  Metal_Clipping.mm
  Metal_Context.hxx
  Metal_Context.mm
  Metal_FrameBuffer.hxx
  Metal_FrameBuffer.mm
  Metal_GraphicDriver.hxx
  Metal_GraphicDriver.mm
  Metal_GraphicDriverFactory.hxx
  Metal_GraphicDriverFactory.mm
  Metal_Group.hxx
  Metal_Group.mm
  Metal_IndexBuffer.hxx
  Metal_IndexBuffer.mm
  Metal_PrimitiveArray.hxx
  Metal_PrimitiveArray.mm
  Metal_Resource.hxx
  Metal_Resource.mm
  Metal_Sampler.hxx
  Metal_Sampler.mm
  Metal_ShaderManager.hxx
  Metal_ShaderManager.mm
  Metal_Structure.hxx
  Metal_Structure.mm
  Metal_Texture.hxx
  Metal_Texture.mm
  Metal_UniformBuffer.hxx
  Metal_UniformBuffer.mm
  Metal_VertexBuffer.hxx
  Metal_VertexBuffer.mm
  Metal_View.hxx
  Metal_View.mm
  Metal_Window.hxx
  Metal_Window.mm
  Metal_Workspace.hxx
  Metal_Workspace.mm
)
