# Source files for Metal package
set(OCCT_Metal_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Metal_FILES
  Metal_AspectState.hxx
  Metal_BackgroundRenderer.hxx
  Metal_BackgroundRenderer.mm
  Metal_Buffer.hxx
  Metal_Buffer.mm
  Metal_CappingAlgo.hxx
  Metal_CappingAlgo.mm
  Metal_Caps.hxx
  Metal_Caps.mm
  Metal_Clipping.hxx
  Metal_Clipping.mm
  Metal_ComputeEncoder.hxx
  Metal_ComputeEncoder.mm
  Metal_ComputePipeline.hxx
  Metal_ComputePipeline.mm
  Metal_Context.hxx
  Metal_Context.mm
  Metal_Font.hxx
  Metal_Font.mm
  Metal_Flipper.hxx
  Metal_Flipper.mm
  Metal_FrameBuffer.hxx
  Metal_FrameBuffer.mm
  Metal_FrameStats.hxx
  Metal_FrameStats.mm
  Metal_GraduatedTrihedron.hxx
  Metal_GraduatedTrihedron.mm
  Metal_GraphicDriver.hxx
  Metal_GraphicDriver.mm
  Metal_GraphicDriverFactory.hxx
  Metal_GraphicDriverFactory.mm
  Metal_Group.hxx
  Metal_Group.mm
  Metal_IndexBuffer.hxx
  Metal_IndexBuffer.mm
  Metal_InstanceBuffer.hxx
  Metal_InstanceBuffer.mm
  Metal_Layer.hxx
  Metal_LayerFilter.hxx
  Metal_LayerList.hxx
  Metal_LayerList.mm
  Metal_LineAttribs.hxx
  Metal_OIT.hxx
  Metal_OIT.mm
  Metal_PBREnvironment.hxx
  Metal_PBREnvironment.mm
  Metal_PointSprite.hxx
  Metal_PointSprite.mm
  Metal_PostProcess.hxx
  Metal_PostProcess.mm
  Metal_PrimitiveArray.hxx
  Metal_PrimitiveArray.mm
  Metal_RayTracing.hxx
  Metal_RayTracing.mm
  Metal_RenderFilter.hxx
  Metal_Resource.hxx
  Metal_Resource.mm
  Metal_Sampler.hxx
  Metal_Sampler.mm
  Metal_ShaderManager.hxx
  Metal_ShaderManager.mm
  Metal_StencilOps.hxx
  Metal_StereoComposer.hxx
  Metal_StereoComposer.mm
  Metal_Structure.hxx
  Metal_Structure.mm
  Metal_Text.hxx
  Metal_Text.mm
  Metal_Texture.hxx
  Metal_Texture.mm
  Metal_UniformBuffer.hxx
  Metal_UniformBuffer.mm
  Metal_VertexBuffer.hxx
  Metal_VertexBuffer.mm
  Metal_View.hxx
  Metal_View.mm
  Metal_Window.hxx
  Metal_Window.mm
  Metal_Workspace.hxx
  Metal_Workspace.mm
)
